#!/bin/bash

# Configuration des flags d'erreur pour bash
set -o errexit
set -o pipefail
set -o nounset

postgres_ready() {
python << END_PYTHON
import sys

import psycopg2

try:
    psycopg2.connect(
        dbname="${POSTGRES_DB}",
        user="${POSTGRES_USER}",
        password="${POSTGRES_PASSWORD}",
        host="${POSTGRES_HOST}",
        port="${POSTGRES_PORT}",
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)
END_PYTHON
}

# On attend que la base de donnée Postgresql soit prête à accueillir des connexions
# PSEUDO CODE
# Tant que je n'arrive pas à me connecter à la base postgresql
until postgres_ready; do
#   afficher un message
    >&2 echo 'Waiting for Postgresql...'
#   attendre une seconde
    sleep 1
# Fin tant que
done

>&2 echo 'Postgresql is ready !'

# On exécute la commande définie dans docker-compose.yml
exec "$@"