#!/bin/bash

# Configuration des flags d'erreur pour bash
set -o errexit
set -o pipefail
set -o nounset

# Lancement des commandes au démarrage du container
python manage.py migrate
python manage.py runserver