version: '3'

django:
  build:
    context: .
    dockerfile: ./compose/local/django/Dockerfile
  image: webinaire_local_django
  depends_on:
    - postgres
  volumes:
    - .:/app
  env_file:
    - ./.env
  ports:
    - 8000:8000
  command: /start

services:
  postgres:
    image: postgres:14
    container_name: postgres
    env_file:
      - ./.env
    # Plus besoin d'exposer les ports à l'extérieur. Seule l'app Django va y accéder (Ouverture du port 8000 dans le container django)
    # ports:
    #   - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: {}