version: '3'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: {}